# Generated by Django 5.2.8 on 2026-02-03 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('MANAGER', 'Manager'), ('FRONT_DESK', 'Front Desk'), ('WORKER', 'Worker'), ('STAFF', 'Staff')], default='STAFF', max_length=20),
        ),
    ]
