# Generated by Django 5.2.8 on 2025-11-25 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('operations', '0001_initial'),
        ('services', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('points_per_dollar', models.DecimalField(decimal_places=2, default=1, help_text='Points earned per dollar spent', max_digits=5)),
                ('points_expiry_days', models.IntegerField(blank=True, help_text='Days until points expire (null = never)', null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LoyaltyTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(choices=[('BRONZE', 'Bronze'), ('SILVER', 'Silver'), ('GOLD', 'Gold'), ('PLATINUM', 'Platinum')], max_length=20)),
                ('min_points_required', models.IntegerField(help_text='Minimum total points to achieve this tier')),
                ('points_multiplier', models.DecimalField(decimal_places=2, default=1.0, help_text='e.g. 1.5 for 50% bonus', max_digits=3)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Tier-specific discount %', max_digits=5)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'ordering': ['min_points_required'],
            },
        ),
        migrations.CreateModel(
            name='CustomerLoyalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_points', models.IntegerField(default=0, help_text='Lifetime points earned')),
                ('available_points', models.IntegerField(default=0, help_text='Points available for redemption')),
                ('tier_achieved_date', models.DateField(blank=True, null=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty', to='customers.customer')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('current_tier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='loyalty.loyaltytier')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PointTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('points', models.IntegerField()),
                ('transaction_type', models.CharField(choices=[('EARNED', 'Earned'), ('REDEEMED', 'Redeemed'), ('EXPIRED', 'Expired')], max_length=20)),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_loyalty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='loyalty.customerloyalty')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_transactions', to='operations.job')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RedemptionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('points_required', models.IntegerField()),
                ('redemption_type', models.CharField(choices=[('DISCOUNT', 'Discount'), ('FREE_SERVICE', 'Free Service')], max_length=20)),
                ('discount_value', models.DecimalField(blank=True, decimal_places=2, help_text='Discount amount if type is DISCOUNT', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('free_service', models.ForeignKey(blank=True, help_text='Service if type is FREE_SERVICE', null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.service')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
