# Generated by Django 5.2.8 on 2025-12-02 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_car_options_alter_customer_options_and_more'),
        ('loyalty', '0001_initial'),
        ('tenants', '0004_alter_tenant_language'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerloyalty',
            name='current_tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_customers', to='loyalty.loyaltytier'),
        ),
        migrations.CreateModel(
            name='LoyaltyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('points', models.IntegerField(help_text='Can be positive or negative')),
                ('reason', models.TextField()),
                ('transaction_type', models.CharField(choices=[('EARNED', 'Earned'), ('ADJUSTMENT', 'Manual Adjustment'), ('REDEEMED', 'Redeemed'), ('BONUS', 'Bonus'), ('PENALTY', 'Penalty')], default='ADJUSTMENT', max_length=20)),
                ('adjusted_by', models.ForeignKey(blank=True, help_text='Admin who made the adjustment', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_adjustments', to='customers.customer')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Loyalty Transaction',
                'verbose_name_plural': 'Loyalty Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
