# Generated by Django 5.2.8 on 2025-11-29 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish')], default='en', help_text='Default language for all users in this tenant', max_length=10),
        ),
    ]
