# Generated by Django 5.2.8 on 2025-12-01 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_tenant_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('am', 'Amharic')], default='en', help_text='Default language for all users in this tenant', max_length=10),
        ),
    ]
