# Generated by Django 5.2.8 on 2025-12-02 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_references', '0001_initial'),
        ('customers', '0001_initial'),
        ('loyalty', '0001_initial'),
        ('tenants', '0004_alter_tenant_language'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['-created_at'], 'verbose_name': 'Car', 'verbose_name_plural': 'Cars'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='car',
            name='car_type',
            field=models.CharField(blank=True, choices=[('SEDAN', 'Sedan'), ('SUV', 'SUV'), ('VAN', 'Van'), ('TRUCK', 'Truck'), ('COUPE', 'Coupe'), ('HATCHBACK', 'Hatchback'), ('WAGON', 'Wagon'), ('CONVERTIBLE', 'Convertible'), ('OTHER', 'Other')], max_length=50),
        ),
        migrations.AddField(
            model_name='car',
            name='corporate_car_id',
            field=models.CharField(blank=True, help_text='Fleet ID for corporate vehicles', max_length=100),
        ),
        migrations.AddField(
            model_name='car',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='make_text',
            field=models.CharField(blank=True, help_text='Legacy field - use make FK instead', max_length=100),
        ),
        migrations.AddField(
            model_name='car',
            name='mileage',
            field=models.IntegerField(blank=True, help_text='Current mileage', null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='model_text',
            field=models.CharField(blank=True, help_text='Legacy field - use model FK instead', max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='company_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='customer',
            name='country',
            field=models.CharField(default='Ethiopia', max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='current_tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='loyalty.loyaltytier'),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('CORPORATE', 'Corporate')], default='INDIVIDUAL', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='house_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='loyalty_points',
            field=models.IntegerField(default=0, help_text='Current available loyalty points'),
        ),
        migrations.AddField(
            model_name='customer',
            name='qr_code',
            field=models.CharField(blank=True, db_index=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='sex',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other'), ('PREFER_NOT_TO_SAY', 'Prefer not to say')], max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='tier_achieved_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='tin_number',
            field=models.CharField(blank=True, help_text='Tax Identification Number', max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='total_lifetime_points',
            field=models.IntegerField(default=0, help_text='Total points ever earned'),
        ),
        migrations.AlterField(
            model_name='car',
            name='make',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='car_references.carmake'),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='car_references.carmodel'),
        ),
        migrations.AlterField(
            model_name='car',
            name='plate_number',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['plate_number'], name='customers_c_plate_n_84d99a_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['is_deleted'], name='customers_c_is_dele_8415e3_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['phone_number'], name='customers_c_phone_n_cabfe1_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['qr_code'], name='customers_c_qr_code_21c71e_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['customer_type'], name='customers_c_custome_47da94_idx'),
        ),
    ]
