# Generated by Django 5.2.8 on 2026-02-03 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_car_options_alter_customer_options_and_more'),
        ('operations', '0002_jobqcrecord_qcchecklistitem_qcchecklistresponse'),
        ('services', '0002_service_image_alter_service_duration_minutes_and_more'),
        ('tenants', '0004_alter_tenant_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='qcchecklistitem',
            name='service',
            field=models.ForeignKey(blank=True, help_text='If null, applies to all jobs (Global)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qc_items', to='services.service'),
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticket_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('customer_type', models.CharField(choices=[('REGISTERED', 'Registered'), ('GUEST', 'Guest')], default='REGISTERED', max_length=20)),
                ('customer_name', models.CharField(help_text='Guest name or cached registered customer name', max_length=200)),
                ('car_info', models.CharField(help_text='Car description for guests or cached info', max_length=200)),
                ('car_plate', models.CharField(blank=True, max_length=20, null=True)),
                ('car_type', models.CharField(blank=True, help_text='SEDAN, SUV, TRUCK, VAN', max_length=50, null=True)),
                ('phone_number', models.CharField(blank=True, help_text='For SMS notifications', max_length=20, null=True)),
                ('status', models.CharField(choices=[('CHECKED_IN', 'Checked In'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED_WAITING_PICKUP', 'Completed - Waiting Pickup'), ('PAID', 'Paid')], default='CHECKED_IN', max_length=30)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tip', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_method', models.CharField(blank=True, choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('ACCOUNT', 'Account')], max_length=20, null=True)),
                ('payment_confirmation', models.CharField(blank=True, help_text='3rd party confirmation number', max_length=100, null=True)),
                ('checked_in_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='customers.car')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='customers.customer')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'ordering': ['-checked_in_at'],
            },
        ),
        migrations.CreateModel(
            name='VisitService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price at time of booking', max_digits=10)),
                ('is_addon', models.BooleanField(default=False, help_text='True if this is an add-on service')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_services', to='operations.visit')),
            ],
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['ticket_id'], name='operations__ticket__fc7c87_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['status'], name='operations__status_4dd88a_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['customer_type'], name='operations__custome_b5bc87_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['phone_number'], name='operations__phone_n_d898fb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='visitservice',
            unique_together={('visit', 'service')},
        ),
    ]
