# Generated by Django 5.2.8 on 2025-12-01 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_systemnotification'),
        ('tenants', '0004_alter_tenant_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemnotification',
            name='category',
            field=models.CharField(blank=True, choices=[('JOB_CREATED', 'Job Created'), ('JOB_ASSIGNED', 'Job Assigned'), ('JOB_STARTED', 'Job Started'), ('JOB_COMPLETED', 'Job Completed'), ('JOB_CANCELLED', 'Job Cancelled'), ('PAYMENT_RECEIVED', 'Payment Received'), ('PAYMENT_FAILED', 'Payment Failed'), ('INVOICE_GENERATED', 'Invoice Generated'), ('PAYMENT_DUE', 'Payment Due'), ('LOW_STOCK', 'Low Stock'), ('OUT_OF_STOCK', 'Out of Stock'), ('STOCK_REPLENISHED', 'Stock Replenished'), ('NEW_CUSTOMER', 'New Customer'), ('LOYALTY_MILESTONE', 'Loyalty Milestone'), ('LOYALTY_REWARD_EARNED', 'Loyalty Reward Earned'), ('SYSTEM_ALERT', 'System Alert'), ('SYSTEM_ERROR', 'System Error'), ('SYSTEM_UPDATE', 'System Update')], help_text='Business-specific notification category', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='RoleNotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('MANAGER', 'Manager'), ('STAFF', 'Staff')], max_length=20)),
                ('job_created_enabled', models.BooleanField(default=True)),
                ('job_assigned_enabled', models.BooleanField(default=True)),
                ('job_started_enabled', models.BooleanField(default=True)),
                ('job_completed_enabled', models.BooleanField(default=True)),
                ('job_cancelled_enabled', models.BooleanField(default=True)),
                ('payment_received_enabled', models.BooleanField(default=True)),
                ('payment_failed_enabled', models.BooleanField(default=True)),
                ('invoice_generated_enabled', models.BooleanField(default=True)),
                ('payment_due_enabled', models.BooleanField(default=True)),
                ('low_stock_enabled', models.BooleanField(default=True)),
                ('out_of_stock_enabled', models.BooleanField(default=True)),
                ('stock_replenished_enabled', models.BooleanField(default=False)),
                ('new_customer_enabled', models.BooleanField(default=True)),
                ('loyalty_milestone_enabled', models.BooleanField(default=True)),
                ('loyalty_reward_earned_enabled', models.BooleanField(default=False)),
                ('system_alert_enabled', models.BooleanField(default=True)),
                ('system_error_enabled', models.BooleanField(default=True)),
                ('system_update_enabled', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Role Notification Preference',
                'verbose_name_plural': 'Role Notification Preferences',
                'db_table': 'role_notification_preferences',
                'ordering': ['role'],
                'unique_together': {('tenant', 'role')},
            },
        ),
    ]
